Class ScreenEffects : EventHandler
{
	bool picloaded;
	TextureID pic;
	int w,h;
	
	override void WorldTick()
	{   
		if (!picloaded)
		{
			pic = TexMan.CheckForTexture ("BLODSCRN", TexMan.Type_Any);
			picloaded = true;
		}    
		[w,h] = TexMan.GetSize(pic);   
	}
	
	override void renderOverlay(RenderEvent e)    // UI scope
	{   
		if(picloaded)
			screen.DrawTexture (pic, true, 320/2 - w/2, 205/2 - h/2, DTA_Clean, true, DTA_Fullscreen, true);
	}
}