Class BloodSmear1 : FlatProps
{	States	{
	Spawn:
		FLAT E -1 NoDelay { bSPRITEFLIP = RandomPick(0,1); }	Stop;
}	}

Class BloodSmear2 : FlatProps
{	States	{
	Spawn:
		FLAT F -1 NoDelay { bSPRITEFLIP = RandomPick(0,1); }	Stop;
}	}

Class BloodSplat1 : FlatProps
{	States	{
	Spawn:
		FLAT G -1 NoDelay { bSPRITEFLIP = RandomPick(0,1); }	Stop;
}	}

Class BloodSplat2 : FlatProps
{	States	{
	Spawn:
		FLAT H -1 NoDelay { bSPRITEFLIP = RandomPick(0,1); }	Stop;
}	}